"""empty message

Revision ID: 1cff01c991d3
Revises: 
Create Date: 2023-05-27 17:46:21.818476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cff01c991d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power_demand', sa.String(length=255), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    # ### end Alembic commands ###
