"""empty message

Revision ID: 623b85c56e83
Revises: ee84be5558fd
Create Date: 2023-05-30 18:40:47.163921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623b85c56e83'
down_revision = 'ee84be5558fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.alter_column('fft',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.alter_column('fft',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
