"""empty message

Revision ID: 8aef3e77a395
Revises: 623b85c56e83
Create Date: 2023-05-30 18:43:38.932714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8aef3e77a395'
down_revision = '623b85c56e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fft_result', sa.JSON(), nullable=False))
        batch_op.drop_column('fft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fft', sqlite.JSON(), nullable=False))
        batch_op.drop_column('fft_result')

    # ### end Alembic commands ###
