"""empty message

Revision ID: e65f2032e64a
Revises: fa9d5e4aedc5
Create Date: 2023-05-30 18:54:32.151767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65f2032e64a'
down_revision = 'fa9d5e4aedc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.alter_column('fft_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.alter_column('fft_string',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
