"""empty message

Revision ID: ee84be5558fd
Revises: 1cff01c991d3
Create Date: 2023-05-29 00:19:29.674068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee84be5558fd'
down_revision = '1cff01c991d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fft', sa.String(), nullable=False))
        batch_op.drop_column('power_demand')
        batch_op.drop_column('geo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geo_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('power_demand', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('fft')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
