"""empty message

Revision ID: fa9d5e4aedc5
Revises: 8aef3e77a395
Create Date: 2023-05-30 18:50:11.235106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fa9d5e4aedc5'
down_revision = '8aef3e77a395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fft_string', sa.String(), nullable=False))
        batch_op.drop_column('fft_result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fft_result', sqlite.JSON(), nullable=False))
        batch_op.drop_column('fft_string')

    # ### end Alembic commands ###
